# Traefik configuration for AeroSafe Documentation
api:
  dashboard: true
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: aerosafe-docs-network

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@aerosafe.it
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web
      # Uncomment for DNS challenge if needed
      # dnsChallenge:
      #   provider: cloudflare
      #   delayBeforeCheck: 30

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Logging
log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep